//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public string version { get; set; }
        public System.Guid id { get; set; }
        public string nombre { get; set; }
        public string fax { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
    }
}
